'use strict'
// 1行目に記載している 'use strict' は削除しないでください
const myPlantsCollection = [
{
    Name: "リドレー",
    Type: "ビカクシダ",
    Habitat: "東南アジア",
    Date: "2017/07/15",  
    MainImage: "./img/ridleyi02.jpg",
    Images:[],
    IntroductionText:"キャベツの様な貯水葉と鹿の角の様な胞子葉。正に鹿角(ビカク)。",
},
{
    Name: "ビフルカツム",
    Type: "ビカクシダ",
    Habitat: "オーストラリア北東部",
    Date: "2015/08/頃",  
    MainImage: "./img/bifur.jpg",
    Images:[],
    IntroductionText:"小さな子株からよくここまで、、、",
},
{
    Name: "グランデ",
    Type: "ビカクシダ",
    Habitat: "東南アジア",
    Date: "2016/03/頃",  
    MainImage: "./img/grande01.jpg",
    Images:[],
    IntroductionText:"見た目のインパクト。ちょっと大きくなり過ぎた、、、",
},
{
    Name: "アンゴレンセ",
    Type: "ビカクシダ",
    Habitat: "アフリカ中央部",
    Date: "2019/07/頃",  
    MainImage: "./img/ango.jpg",
    Images:[],
    IntroductionText:"ゾウの耳の様な立派な胞子葉が魅力的。子株が出来やすい。",
},
// {
//     Name: "サラセニア",
//     Type: "サラセニア",
//     Habitat: "北米",
//     Date: "2021/08/頃",  
//     MainImage: "./img/sarasenia01.jpg",
//     Images:[],
//     IntroductionText:"赤い葉脈が魅力。花が咲くとは思って無かったな",
// },
// {
//     Name: "ガジュマル",
//     Type: "ガジュマル",
//     Habitat: "熱帯、亜熱帯",
//     Date: "2024/08/頃",  
//     MainImage: "./img/gajyu.jpg",
//     Images:[],
//     IntroductionText:"娘がお祭りのイベントでゲット！（この写真ではガジュマルの魅力が、、、）",
// },
]
